apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-operator-db-auth
type: Opaque
stringData:
  username: "<operator-db-user>"
  password: "<operator-db-password>"
---
apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-userlist
type: Opaque
stringData:
  userlist.txt: |
    "<operator-db-user>" "<operator-db-password>"
    "<pgbouncer-user>" "<md5-or-scram-secret>"
